pipeline {
  agent any

  tools {
    nodejs 'nodejs-20.3.1' // Replace 'nodejs' with the name of your Node.js installation in Jenkins
  }
  
  stages {
    stage('test script') {
      steps {
        sh './scripts/test.sh'
      }
    }

    stage('Init') {
      // Setup
      steps {
        sh 'npm install'
      }
    }

    stage('Test') {
      // Build test image and run test image
      steps {
        sh 'npm run test'
      }
    }

    stage('Build') {
      // Build production image
      steps {
        sh 'npm run build'
      }
    }

    stage('Deploy') {
      // rollout restart 
      input {
        message "Please select environment"
        ok "Submit"
        submitter "akaadmin,137487842+robert-wan-sos"
        submitterParameter: 'approverId'
        parameters {
          choice choices: ['Prod', 'Pre-Prod'], name: 'envType'
        }

      }

      steps {
        echo "Deployment approved to ${envType} by ${approverId}."

        sh 'npm run deploy'
        
      }
    }
  }
}
